# fly.toml app configuration file generated for phonebooky on 2023-07-19T11:29:50+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebooky"
primary_region = "arn"

[env]
  PORT = "8080" # lisätään tämä

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080 
  processes = ["app"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
